name: redux_logging
description: Redux.dart Middleware that prints the latest action & state
version: 0.5.1
homepage: https://github.com/brianegan/redux_logging

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  redux: ">=5.0.0 <6.0.0"
  logging: ">=1.0.0 <1.2.0"

dev_dependencies:
  test: ^1.16.5
  pedantic: ^1.11.0
